title: Robert's blog on GitHub
author: robertgarrigos
email: robert@garrigos.cat
description: > # this means to ignore newlines until "baseurl:"
  My new texsting blog on GitHub
 baseurl:

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
